### ISSUE TITLE
UI Flow Diagram V1

### ISSUE THREAD

**Issue by JordanEllis6809** [JingyuZ/GithubColony#10]
- [ ] Colony Login First
- [ ] Domain Selection
- [ ] GitHub Login
- [ ] Task Selection + Import Data
- [ ] Modify Task List Before Upload
- [ ] Upload To Colony
- [ ] ...

**Comment by JordanEllis6809** [comment]
Chatted with Patrick today, he created some pencil & paper prototypes, and is working on making the digital versions now.

**Comment by JingyuZ** [comment]
This issue was moved to colonyportal/GithubColony#2
