### ISSUE TITLE
Task Creation

### ISSUE THREAD

**Issue by JordanEllis6809** [JingyuZ/GithubColony#13]
- [ ] Create a generic interface for a "task".
- [ ] Display a list of a domain currently has.
- [ ] Allow the user to create a task and add it to the colony.

**Comment by JordanEllis6809** [comment]
https://joincolony.github.io/colonyjs/docs-task-lifecycle/

https://joincolony.github.io/colonynetwork/docs-tasks/

**Comment by JingyuZ** [comment]
This issue was moved to colonyportal/GithubColony#3
