### ISSUE TITLE
Improved Wallet Handling

### ISSUE THREAD

**Issue by JordanEllis6809** [JingyuZ/GithubColony#16]
For wallets there are a few different use cases we should support, as detailed here:
https://docs.ethers.io/ethers.js/html/api-wallet.html#creating-instances

We want to make sure we can support wallets that are cold wallets, wallets from other programs like Geth, and wallets from extensions like MetaMask.

Allow the user to choose what type of wallet they want to use with the dApp through a settings menu or something like that.

**Comment by JingyuZ** [comment]
This issue was moved to colonyportal/GithubColony#5
