### ISSUE TITLE
Improved Provider Handling

### ISSUE THREAD

**Issue by JordanEllis6809** [JingyuZ/GithubColony#18]
Currently we're using a localhost provider. We should also be able to support MetaMask as a provider. Allowing the user to choose through a settings menu would be nice.

Others would be nice (like public full nodes, or a local node), but for the hackathon we could require MetaMask.

Here's an example implementation:
https://dev.to/yukkurisinai/using-metamask-as-web3js-provider-2do4

**Comment by JordanEllis6809** [comment]
https://web3js.readthedocs.io/en/1.0/web3.html#providers

**Comment by JingyuZ** [comment]
This issue was moved to colonyportal/GithubColony#7
