### ISSUE TITLE
Auto-Deploy to IPFS

### ISSUE THREAD

**Issue by JordanEllis6809** [JingyuZ/GithubColony#9]
- [ ] Stand up a simple server that automatically deploys the latest build of our app to IPFS.
- [ ] The domain forwards to the server which forwards to the latest IPFS URL.
- [ ] The simple server also supports getting the IPFS URL so we can setup the final "production" domain to forwards straight to that.

**Comment by JingyuZ** [comment]
This issue was moved to colonyportal/GithubColony#1
